# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-10-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('in_use', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('owner', models.TextField(max_length=30)),
                ('tag', models.TextField(max_length=10)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
